### ISSUE TITLE
Write descriptions for all of the modules

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/onramp#126]

**Comment by TammyTee** [comment]
@mattstauffer Here's my try at the descriptions. I have a draft PR that will add the description field to the Module Resource so that these can be easily updated on the live site after you've provided feedback/made adjustments.

### All Modules

- **Build a basic website**
Building a website can unlock a whole set of opportunities.

- **Basic Terminal & Git**
Master navigating the command line and code versioning concepts to increase your productivity as a developer.

- **Local PHP Environment**
Prepare your local development environment before you install and configure your first Laravel application.

- **Beginning PHP**
Start building dynamic, interactive web applications by learning one of the most widely used languages on the web.

- **Object-Oriented Programming**
Gain foundational knowledge of writing a clean, modular computer program by learning key concepts including Inheritance, Polymorphism, Abstraction and Encapsulation.

- **Laravel Basics**
A great starting point for developers that are new to the Laravel framework and its features.

- **Basic Javascript**
Use this to turn your basic website into a dynamic web experience and start thinking like a programmer.

- **Laravel Mix**
Ease into module-bundler configuration with a Webpack wrapper that's completely optimized for use with Laravel.

- **Basic session-backed internal APIs**
--

- **Deployments**
Want to ship valuable features out faster? Add continuous integration and deployment techniques into your workflow.

- **Monitoring (e.g. Bugsnag)**
Stay on top of your applications performance even during development to provide your application's users with a greater experience.

- **Basic Testing**
Detect problems and areas of improvement in your code faster with test driven development.

- **Basic Dev-Ops**
Seamlessly move your applications from development and into production.

### WordPress Only Modules

- **Local PHP Environment**
Configuring your local environment for development outside of WordPress.

- **Laravel Basics**
-- *Not sure that this needs to be so different from the original*

- **Why Laravel / Laravel vs WP / Pros and Cons of Laravel for WP developers**
Learn the differences between Laravel and WordPress and why you might choose Laravel instead.

- **Mapping the WP concepts**
Taking concepts you're already familiar with like themes and hooks, and seeing how they might be accomplished using Laravel.

**Comment by mattstauffer** [comment]
Great! Just a few additions and edits:

Easy session-backed internal APIs:
Learn to build simple APIs with Laravel that will power your app's JavaScript with almost no code.

Deployments:
Learn how to use powerful tools like Laravel Forge to spin up your own servers and automatically deploy your code to it from GitHub.

Monitoring:
Stay on top of your applications performance even during development to learn when the app broke for your users.

Basic Testing:
Write code that asserts its own behavior to help you start and stay confident it does what it should.

Basic Dev-Ops:
Manage your servers and the rest of your deployment infrastructure yourself.

Why Laravel / Laravel vs WP / Pros and Cons of Laravel for WP developers:
Learn the differences between Laravel and WordPress and why you might choose to use Laravel for a project.
