### ISSUE TITLE
When a user changes the language in the dropdown, also change it in their user preferences

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/onramp#135]

**Comment by rosswintle** [comment]
I popped in to have a look at this as @mattstauffer suggested people grab this issue in Telegram chat.

I've not been keeping up with all the live streams but decided to take a look. Initially I couldn't see what was required but then I dug in and realised what was needed. I think.

First of all - correct me if I'm wrong - preferences only apply to registered users, and so this will only be needed for logged in users. Is that right?

I see two ways to do this:

1. Use a middleware that compares the current locale to the user preferences locale and sets the user preference if they are different. Seems a bit heavy-handed to do this on every request. But that probably shouldn't worry us for such a quick check.

2. Add click handlers to the language switcher links so that they make an Axios/AJAX call to the `user.preferences.store` route in the same way that `ResourceLanguagePreferenceSwitcher.vue` does, and then send the user to the correct locale.

**Comment by mattstauffer** [comment]
Yep, only logged in users right now.

Good point--right now it's purely a URL switch. I think it'd have to be modifying the dropdown to do exactly what you're saying--set the preference *then* redirect

**Comment by rosswintle** [comment]
As stated in [#136](https://github.com/tightenco/onramp/issues/136#issuecomment-557114719) I think we should have either the cookie (and use it for not-logged-in-users too) OR the preference but not both.

The best change to me seems to be to set the locale cookie for everyone, and ditch the preference. This saves lots of confusion.

But let me know if you disagree and I can have a go at this change.

**Comment by mattstauffer** [comment]
I think we *definitely* want the cookie.

So, let's talk about the costs if we remove the user preference:
- We can't consider language in emails
- We can't log them automatically into their preferred language once they log in (assuming someone would ever log in through the UI in not-their-preferred-language, which seems a bit unlikely but it's possible)
- If we generate links in emails, they wont' be linked to the correct language; they'll have to follow the link to the /en/whatever/link URL, then that will set the cookie as english, then they'll have to change the translation as well

So the biggest one is emails. Thoughts?

**Comment by rosswintle** [comment]
Aha! This is the bit of functional spec I was missing in this discussion!

I see why preference is needed now. My remaining question is whether cookie/dropdown should override it? What's the use case for a change of language updating the preference? Why would someone do this and would they expect it to change their preference?

Options:
 - Stop overthinking it and just sync the darned thing to preferences, Ross!! 😉
 - Remove the dropdown once a preference is set so it can only be changed in preferences
 - Add a notice when the dropdown is changed saying "Do you want to update your language preference too?"
 - Allow the dropdown to be changed, but subsequent pages have a dismissable banner telling you the two are out of sync and offering to update the preference

**Comment by mattstauffer** [comment]
I think 'remove the dropdown once a preference is set' makes the most logical sense BUT is changing the UI in a way that i think is likely to confuse the end user.

OOO. Maybe if you're logged-in, the Language link just pushes you over to the preferences page?

**Comment by keliix06** [comment]
I like the original idea of updating the preference and redirecting, but on top of that I think the user should be notified that that happened. Once the toast notifications from #130 are in, that becomes a trivial task.

If those are being kept in sync, there is no reason to require an extra click just to go to the preferences page to make the change when that functionality can be offered in a more seamless manner.

I do like the idea of setting a cookie for non-authenticated users though, so that their language preference can be honored even if they don't have an account.
