### ISSUE TITLE
Send existing users to the wizard in a non-weird way

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/onramp#137]

**Comment by rontu85** [comment]
@mattstauffer How about somthing like this:

![grafik](https://user-images.githubusercontent.com/1764340/68543655-5ac6cd80-03ba-11ea-853c-b7f86f3c8a15.png)

When you're okay with this, I'd like to implement it. This would only appear if there is are no preferences set in the user model. Otherwise this would not be needed.

**Comment by mattstauffer** [comment]
I think I might rather we put it at the top of the dashboard so it’s not there all the time but then we can make it a much stronger alert just on the dashboard.

**Comment by mattstauffer** [comment]
Most folks are preferring English and there's a language switcher on every page; and the OS doesn't realllly matter that much right now; and we already have this tooling for track. Going to close.
