### ISSUE TITLE
Ensure development environment section covers all 3 major platforms (Win/Mac/Linux)

### ISSUE THREAD

**Issue by bandgeekndb** [tightenco/onramp#15]
While Valet is a fantastic tool, it's only for Mac users and one of the pain points I've experienced myself and heard from others is trying to get a development environment installed on Windows.

If we can provide a simple set of instructions for getting started with development on Windows, that would probably be a great addition to the section on Development Environment.

If no one beats me to it, I'll try to write up some documentation on Homestead, since that works on all 3 platforms and is something I'm comfortable writing about, but that's not necessarily the "simple" setup either.

Maybe some kind of setup guide using XAMPP and `php artisan serve`?

**Comment by matt-allan** [comment]
Is Windows Subsystem for Linux simple enough that a beginner would be able to use it to install Ubuntu and then install PHP?

It seems like it could potentially be simpler since you don't need to learn all of the vagrant commands, it automatically mounts all of your drives, and apparently you can open a shell inside the Linux machine from the 'Bash.exe' application.

Compared to something like XAMPP I imagine it would be easier in the long run as most documentation and tutorials are written assuming you are using a *nix CLI and it might not be clear to a beginner how to translate *nix commands to Powershell.

**Comment by mattstauffer** [comment]
I would *love* if we can recommend WSL and make sure we have a Valet Linux fork to recommend. I think that WSL will make the entire flow, not just Valet, easier, and I much prefer Valet over Homestead, especially for beginners.

**Comment by jonsugar** [comment]
My personal choice for Laravel on Windows would be Laragon. It's WAMP + Terminal + Database App. Easy swapping of PHP version and is similar to valet in that it provides `http://<project name>.test` access. 

My issue with WSL has always been that it forces command line use for phpunit, composer etc. because you can't execute the linux binaries easily from within your windows editor. 

The Laragon approach is much more windows like in my opinion in that its more application focused than cmd line. Having said that, the provided terminal solution does allow for running of bash so that following tutorials that are Mac/linux focused is doable.

**Comment by jonsugar** [comment]
Although this issue is closed I thought I'd make this comment to reflect new developments. 

**Matts comment**
> I would _love_ if we can recommend WSL and make sure we have a Valet Linux fork to recommend. I think that WSL will make the entire flow, not just Valet, easier, and I much prefer Valet over Homestead, especially for beginners.

**and Part of my reply**
> My issue with WSL has always been that it forces command line use for phpunit, composer etc. because you can't execute the linux binaries easily from within your windows editor. With Laragon you can happily run those tools from within your IDE/Editor.

Latest news is that in PhpStorm 2019.3 this issue is being fixed. The PhpStorm will be able to execute the WSL versions of php, composer or phpunit etc.
