### ISSUE TITLE
Implement EU Data protection and privacy compliance.

### ISSUE THREAD

**Issue by jonsugar** [tightenco/onramp#151]
We should add a cookie acceptance widget and decide on our approach to GDPR.

Adding a cookie widget is pretty simple. For example, we could use the [Spatie Cookie Consent](https://github.com/spatie/laravel-cookie-consent) package.

GDPR is more problematic. We need to provide all manner of things in order to comply if we hold personally identifiable information (we do, email addresses). We could just not use email addresses as our unique identity key. After all, we are not using emails for anything (newsletters etc.) or requiring email confirmation.

Regardless of our approach to the above, we should have a terms of service and a privacy policy in any case. The above will make them more complicated I assume.

**Comment by mattstauffer** [comment]
So, my first response is:

@#(*&^$#@$ GDPR and all that EU bullshit.

However, I know that's not a long-term sustainable solution. So, here's my take:

I want this to have as *little* impact on the shape and usability of this site as humanly possible. I don't want a cookie consent package unless it's ABSOLUTELY required and if it is I want it to be very small, simple, transparent, unobtrusive, and ANYTHING else in our power to make it good for the user.

If people are doing things not because it's the right thing but because they're afraid of the GDPR boogeyman, I don't want us to do it.

I want to do the absolute minimum, because every single GDPR and EU usage scenario I've seen has turned the site's usability into garbage and I hate that as an entire concept.

I think having an email address is necessary for notifications and password reset so I don't want to go without that. So, sadly, we'll have to dig into whatever we want to deal with.

Privacy policy is fine. we can generate a random one on the internet somewhere.

Thanks for thinking of this, even if I think it's almost exclusively bullshit; that's not your fault.

**Comment by jonsugar** [comment]
> So, my first response is:
> 
> @#(*&^$#@$ GDPR and all that EU bullshit.
🤣🤣 

My feelings on GDPR and the cookie consent are the same as yours. However, with a sigh in my heart my head says we should consider them.

Re: cookie consent it can be literally as unobtrusive as the pale blue banner that is currently running at the top of onramp. 

Re: GDPR, as far as I understand it if we hold personal information, we need to provide mechanisms for "right to delete" and "right to download" personal data–I'm no lawyer though. Those functions can be as simple as email this address. 

Both of these are massive pains for developers and they both scare me from trying my own projects or side hustles. With my user hat on though I kinda like GDPR. I'm a Lastpass user and hate the facebook/google data tracking so I appreciate the legislation being there. I'm literally, torn between liking and hating GDPR.

**Comment by mattstauffer** [comment]
Yah, I think we need to build:

- Ability for them to download all of their data
- Ability for them to delete all of their data
- Cookie consent thing

Thankfully, none of those will be absolutely miserable.


I'm pro privacy and user consent. I think the EU has made a bunch of stupid decisions. But it's fine in the ways it prompts us to remember to get *ahead* of user privacy/control needs instead of roll behind them. So yah, let's do it.

**Comment by michapietsch** [comment]
EU user here. :)

Disclaimer: Not a lawyer.

Heads up (pun intended): It's all not that crazy after all.

Latest cookie ruling: The problem are non-essentiell cookies (e.g. ads, tracking). No consent needed for session cookie and XSRF token.

Document use of data: Generic policy will not suffice. Because it needs to explain this specific system. But that's not hard to write down. Example: Email address as ID and for notifications, encrypted password for access protection, and completed modules (...) to track personal progress. Not really much different from the brief pitch you would give a new user.

Right to be forgotten: It should be enough to delete the user and all associated progress. Or is there any data critical to the system, that needs to be retained? Probably not. Oh, wait: Log files should not contain sensitive data, or they would need to be cleaned.

Download all data: I recommend: Wait until a first request. Build it only if there are repeated requests.

Deletion could also be done on request. Same with request for all stored data: Basically the latter is not more than what's visible in the profile and modules anyway, right? Except the current password, maybe. ;)

Please note the important difference: If your movie streaming provider logs each time you pause, or go back watch a scene again, that's creepy! But that's not Onramp.

**Comment by jonsugar** [comment]
Thank you @michapietsch. I'm also an EU citizen but much less knowledgable than you!

These all seem like sensible approaches. @mattstauffer do you think we can proceed with these approaches?

**Comment by mattstauffer** [comment]
@michapietsch Thank you -- this is super helpful!

- No cookie consent needed 👌
- Need to write a use of data thing somewhere
- Wait to build tooling for deleting all data until first request 👌
- Wait on download all data until first request👌

Sounds great to me! If someone feels excited to build the delete-all-data or download-all-data tooling, please go ahead! Otherwise the main focus is on documenting use of data somewhere somehow.

**Comment by Woddell** [comment]
Just wanted to add to this regarding cookies (I've known a few companies to be caught out on this). While you don't have to give consent for session cookies (think that's the only ones on onramp), you still have to: 
> Provide accurate and specific information about the data each cookie tracks and its purpose in plain language before consent is received.
source: https://gdpr.eu/cookies/

This will most likely be included in the 'use of data' anyway, but just wanted to point it out in case it's overlooked :-)

**Comment by TammyTee** [comment]
Use of Data page added. See #175
