### ISSUE TITLE
Build tooling to make it possible to add caveats (e.g. Redis works differently on Windows) or OS-specific hints and links

### ISSUE THREAD

**Issue by nicorafales** [tightenco/onramp#48]
Hi!
I want to propose to change the focus of development based on macOS as a de facto platform. Most future developers out there may not have access to a macbook or similar hardware so all the docs should include Windows and GNU/Linux links for tooling instalation and configuration on par with the huge amount of links we can find all over the place for macOS users.
I have been a Laravel (& Symfony) developer for the past 3 years (working on home projects with Windows 10 and at companies using GNU/Linux) and i've yet to try a mac. I don't need it, i don't want it and i don't hate it

**Comment by mattstauffer** [comment]
That's an opportunity for you to contribute to Onramp! I use a Mac; as does Taylor. We know a lot about what works well on Macs. We *don't* know as much about what works well in other settings.

So, we have to rely on people who use those platforms to contribute. It doesn't have to be a "change the focus", it should just be "if you use other tools, contribute".

I would recommend specific suggestions. For example, is this not enough? Is there anything else on Onramp that's actually Mac-specific right now?

<img width="420" alt="image" src="https://user-images.githubusercontent.com/151829/65243789-15bba480-dab7-11e9-94ca-ff5e4cfd9c3d.png">

I will make one caveat: This site will always primarily embody a "happy path". it's not about giving a million options. It's about giving one preferred option. So I'm not going to recommend seven different local dev environments; but I'm fine to recommend a single one per environment.

**Comment by rAfitiiixxx** [comment]
For now, it's only the local environment. But probably when docs get bigger, everything outside of the bounds of Laravel has to have a link to the other OSes. For example, the driver for Redis doesn't work the same way, has less features, in Windows. So subscribing Queue jobs or Horizon doesn't work out of the box without tweaking. Deployments section should be diferent for all three main OSes (not counting I/P/SaaS platforms).
Yeah! we all have to help to contribute to the docs since we work with those configurations. I just wanted to make it visibile so it's a present matter from now on for docs and trainings.

**Comment by mattstauffer** [comment]
Hey Nicolás! You sure did--thanks so much for your patch!

I think there's going to have to be a balance. I _do_ agree that I want us to consider all development stacks. But I also want to focus on "how it works, at its simplest" and have everything else be caveats--links to "if you have this problem here's a solution", rather than having to run everyone through it.

I think it's good for us to consider building in a concept into the platform itself about "adding caveats" or "adding a concept of which OS someone is in" so we can help round the thing out without making it too clumsy. 👍🏻 Thanks for bringing it up!

**Comment by mattstauffer** [comment]
I'm going to re-name the issue so it tracks more of how I'm thinking about it now.

**Comment by jonsugar** [comment]
@mattstauffer I think this can be closed due to #24
