### ISSUE TITLE
Consider bringing in an Open Doodle somewhere on the landing page to make it feel a bit more friendly and less square

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/onramp#84]
https://www.producthunt.com/posts/open-doodles

**Comment by zuzana-kunckova** [comment]
Is the website going to be re-designed at some point or is the current design going to stay? I'd like to do this issue, I'm just thinking if I should keep in mind any future design changes or just do it so that it fits with what we have currently. 

I assume that the blue/purple-ish color is going to stay as a brand color, right?

**Comment by mattstauffer** [comment]
@zuzana-kunckova We do have a real design coming soon, so this is more of a stopgap to just get something a little bit more friendly up there. I expect the color palette will stay pretty similar.

**Comment by zuzana-kunckova** [comment]
@mattstauffer , I'll add a Doodle.

**Comment by zuzana-kunckova** [comment]
@mattstauffer I tried to add a doodle but nothing looks right (seems like my design skills need some work), so I'm going to wait until the final design is done. 
Unless someone else wants to have a go.

**Comment by mattstauffer** [comment]
Haha, no worries! Thanks for taking a look.
